apiVersion: v1
kind: Service
metadata:
  name: service-display-overview-lb
spec:
  selector:
    app.kubernetes.io/name: deployment-overview
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  #clusterIP: 10.100.0.15
  type: ClusterIP
#status:
  #loadBalancer:
   # ingress:
    #- ip: 192.0.2.127